name: sportper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+15

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  json_annotation: ^4.0.0
  json_serializable: ^4.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  path_provider: ^2.0.2
  intl_utils: ^2.4.0
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_messaging: ^14.0.0
  firebase_storage: ^11.0.0
  google_sign_in: ^5.1.0
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.2.0
  uuid: ^3.0.6
  share_plus: ^4.1.0
  image_picker: ^0.8.2
  image_cropper: ^1.4.1
  path: ^1.8.0
  flutter_local_notifications: ^9.2.0
  sign_in_with_apple: ^4.2.0
  crypto: ^3.0.1
  maps_launcher: ^2.0.1
  form_builder_extra_fields: ^8.0.0
  photo_view: ^0.13.0
  geolocator: ^7.7.1

#dependency_overrides:
#  firebase_messaging_platform_interface: 3.1.6
#  cloud_firestore_platform_interface: 5.4.11
#  firebase_auth_platform_interface: 6.1.10
#  firebase_storage_platform_interface: 4.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
        - asset: assets/fonts/Avenir-Regular.ttf
          weight: 400
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Semi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Avenir-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this splash should have a
  # "family" key with the font family name, and a "fonts" key with a
  # splash giving the asset and other descriptors for the font. For
  # sportper:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
